Add support for API documentation
spdx/spdx-online-tools pull request #323
Opened 2021-08-11 11:49 UTC by Ugtan

This PR adds support for API documentation with the help of drf-yasg library.

2021-08-15 06:55 UTC, rtgdk commented
@Ugtan How will this generate swagger specs? Can we host the file on github repo/wiki in some way?

2021-08-15 16:35 UTC, Ugtan commented
This will generate the api documentation on app/swagger and app/redoc endpoint. I don't think so there is any other way to generate it on wiki rather than writing it manually. @rtgdk

2021-08-23 15:54 UTC, rtgdk commented on src/src/urls.py
> +    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
What is redoc/ for?

2021-08-29 17:31 UTC, rtgdk commented
@Ugtan ping

2022-03-13 13:38 UTC, rtgdk requested changes
We need to rethink about drf-yasg module whether it suits our apis. Or we need to change how we model the apis parameters and response and make it visible on the URLs side to make swagger pick up the documentation. This needs to be investigated. Not merging this PR as it doesn't add any value right now.

Let's continue to use the wiki endpoint - https://github.com/spdx/spdx-online-tools/wiki/REST-API-Fields-Request-and-Response for Rest API request and response parameter.

2022-03-13 13:38 UTC, rtgdk commented on src/src/urls.py
> +        license=openapi.License(name="BSD License"),
`Info` needs to be changed.

2022-03-13 13:38 UTC, rtgdk commented on src/api/views.py
> -    if request.method == 'GET':
Why did we remove all `GET` endpoints?

2022-03-13 13:38 UTC, rtgdk commented on src/src/urls.py
> +
The `redoc/` and `swagger/` endpoints are not showing any parameters and response for drf apis, 
<img width="1427" alt="Screenshot 2022-03-13 at 7 02 26 PM" src="https://user-images.githubusercontent.com/17159160/158061923-baa542f6-fd8b-4593-b77c-c254c37fe546.png">

The values are coming up empty. How will drf-yasg pick up parameters information from the serializer defined in views.py file?

2022-03-13 13:38 UTC, rtgdk commented on src/src/settings.py
> +    'corsheaders',
why do we need `corsheader`?

2022-03-13 17:20 UTC, rtgdk commented
@goneall @Ugtan Not merging this to python3 as it doesn't provide any value right now. The swagger spec generated are empty. Maybe we need to rethink where to provide the API request and response structure. drf-yasf doesn't seem to pick up parameters from views.py. Maybe I am missing something here. Open to suggestions on what to do next.

2026-06-25 02:16 UTC, bact commented
Close PRs #323 (drf-yasg for OpenAPI 2 schema + Swagger/Redoc UI) and #451 (Swagger) as they are superseded by #644 (drf-spectacular for OpenAPI 3 schema + Swagger/Redoc UI).

Feel free to open new PR to amend/extend the API doc generation.

2026-06-25 02:16 UTC, closed without merging