Add ntia-conformance-checker compliance selector to UI
spdx/spdx-online-tools pull request #542
Opened 2024-12-22 04:50 UTC by bact

Changes to ntia-conformance-checker related code, to prepare it for more compliance checkers in the future.

- Update ntia-conformance-checker version to 3.0.2
- Add compliance selector to UI
  - There's only one option now, which is the selected default "ntia"
- Add a (commented) code to get compliance request value
  - If the value is not exist, use "ntia" as default
  - This value will be used post-3.0.2 to let SbomChecker knows which compliance it should check against

2024-12-22 19:57 UTC, goneall approved these changes
LGTM

2024-12-23 18:24 UTC, goneall requested changes
I'll do some more testing - may add further comments, but there is one change I found needs to be made with the requirements.txt file.

2024-12-23 18:24 UTC, goneall commented on requirements.txt
>  spdx-tools==0.8.2
```suggestion
spdx-tools==0.8.3
```

NTIA tools version 3.0.2 requires an update to the spdx-tools to 0.8.3

2024-12-23 19:12 UTC, goneall requested changes
A few more changes to fix problems that were present in the previous versions - might as well fix them with this update.

2024-12-23 19:12 UTC, goneall commented on src/app/templates/app/ntia_conformance_checker.html
> +        <option value="XLSX">XLSX Spreadsheet</option>
```suggestion
```

This option isn't supported by the Python libraries - we should remove it from the dropdown options.

2024-12-23 19:12 UTC, goneall commented on src/app/templates/app/ntia_conformance_checker.html
> +        <option value="XLS">XLS Spreadsheet</option>
```suggestion
```

This option isn't supported by the Python libraries - we should remove it from the dropdown options.

2024-12-23 19:12 UTC, goneall commented on src/app/templates/app/ntia_conformance_checker.html
> +        <option value="YAML">YAML</option>
```suggestion
```

This option isn't supported by the Python libraries - we should remove it from the dropdown options.

2024-12-26 18:42 UTC, goneall reviewed
LGTM - It looks like we're about to get a new release of the conformance checker.

@bact - do you want to wait for the new release before merging?

2024-12-27 19:07 UTC, goneall approved these changes
Everything tests out fine, so I'm going to go ahead and merge this PR.

If we decide to include a new release of the NTIA Conformance Checker, we can create a second PR.

2024-12-27 19:07 UTC, merged

2024-12-27 20:04 UTC, bact commented
Thank you. I will create another PR after we have the new release of the checker.